parameters:
  ServiceConnectionAzure: ""

steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Get-ChildItem -Path Env:
    displayName: 'Display Variables'

  - download: azureRepo
    name: Download_Repo
    displayName: 'Download Artifact from Build-general pipeline'

  - powershell: Get-ChildItem -Path $(Pipeline.Workspace) -Recurse -Force
    displayName: 'Listing Checkout files'

  # - task: AzurePowerShell@5
    # name: Remove_RG
    # inputs:
    #   azureSubscription: ${{ parameters.ServiceConnectionAzure }}
    #   ScriptType: 'InlineScript'
    #   Inline: |
    #     Remove-AzResourceGroup -Name "$(resourceGroupName)" -Force
    #   azurePowerShellVersion: 'LatestVersion'
    # displayName: 'Remove RG - $(resourceGroupName)'

  - task: AzureCLI@2
    condition: succeeded()
    inputs:
      azureSubscription: ${{ parameters.ServiceConnectionAzure }}
      scriptType: 'pscore'
      workingDirectory: '$(Pipeline.Workspace)/azureRepo/Repo/IaC'
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Host "Initialize Terraform Init"
        terraform init
        Write-Host "------------------------------------------------------------" 
        Write-Host "Terraform Validate"
        terraform validate
        Write-Host "------------------------------------------------------------"
        Write-Host "Terraform Plan"
        terraform plan 
        Write-Host "------------------------------------------------------------"
        Write-Host "Terraform apply"
        terraform apply -auto-approve

      continueOnError: true
    displayName: 'Deploy Terraform Infrastructure'
