parameters:
  ServiceConnectionACR: ""

steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Get-ChildItem -Path Env:
    displayName: 'Display Variables'

  - download: azureRepo
    name: Download_Repo
    displayName: 'Download Artifact from Build-general pipeline'

  - powershell: Get-ChildItem -Path $(Pipeline.Workspace) -Recurse -Force
    displayName: 'Listing Checkout files'

  - task: Docker@2
    condition: succeeded()
    inputs:
      containerRegistry: ${{ parameters.ServiceConnectionACR }}
      repository: '$(acrName)'
      command: 'buildAndPush'
      Dockerfile: '$(Pipeline.Workspace)/azureRepo/Repo/Dockerfile'
      tags: 'latest'
